### ISSUE TITLE
Add an end offset

### ISSUE THREAD

**Issue by daamsie** [bbecquet/Leaflet.PolylineDecorator#40]
The offset at the moment is only for the start of the polyline. I had a need to provide an offset at the end as well.

My proposal is to add a new option "endoffset" with the same behaviour as offset, but for the end of the polyline. 

Alternatively, "offset" could be renamed to "startoffset" and "offset" could instead be shorthand for setting startoffset and endoffset at the same time. 

I already have worked around this in a local version of the code and happy to contribute back whichever style is preferred.

**Comment by bbecquet** [comment]
Hi, and thanks for your contribution!
I see how this end offset behaviour can be useful, that's a good idea to add it.

About the name, I think the first option (`offset` and `endOffset`) is better, because it doesn't break the current API, it just adds something to it.

I'll add other comments on your pull request.
